#index:
#    path: /
#    defaults: { _controller: 'Hank\Controller\DefaultController::index' }

#Homepage
hank_homepage:
  path: /
  controller: Hank\UI\Symfony\Controller\BankHomePageController::index

#Client Panel
hank_client_panel:
  path: /client-panel
  controller: Hank\UI\Symfony\Controller\ClientPanelController::index

hank_client_panel_change_background_processing:
  path: /client-panel/processing/change-background
  controller: Hank\UI\Symfony\Controller\ClientPanelController::changeClintBackground

hank_client_panel_change_avatar_processing:
  path: /client-panel/processing/change-avatar
  controller: Hank\UI\Symfony\Controller\ClientPanelController::changeClientAvatar

#Send money to friends
hank_send_money_to_friends:
  path: /client-panel/send-money
  controller: Hank\UI\Symfony\Controller\SendMoneyToFriendsController::index

hank_send_money_to_friends_processing:
  path: /client-panel/processing/send-money
  controller: Hank\UI\Symfony\Controller\SendMoneyToFriendsController::send

#Sign In
hank_sign_in:
  path: /sign-in
  controller: Hank\UI\Symfony\Controller\SignInController::index

#Sign Up
hank_sign_up:
  path: /sign-up
  controller: Hank\UI\Symfony\Controller\SignUpController::index

#Sign Up Processing
hank_sign_up_processing:
  path: /processing/sign-up
  controller: Hank\UI\Symfony\Controller\SignUpController::signUp

#Sign Out:
logout:
  path: /sign-out

#Pay In
hank_pay_in_client_panel:
  path: /client-panel/pay-in
  controller: Hank\UI\Symfony\Controller\PayInController::index

#Pay In Processing
hank_pay_in_processing:
  path: /client-panel/processing/pay-in
  controller: Hank\UI\Symfony\Controller\PayInController::payIn
  methods: [POST]

#Pay Out
hank_pay_out_client_panel:
  path: /client-panel/pay-out
  controller: Hank\UI\Symfony\Controller\PayOutController::index

#Pay Out Processing
hank_pay_out_processing:
  path: /client-panel/processing/pay-out
  controller: Hank\UI\Symfony\Controller\PayOutController::payOut
  methods: [POST]
