#index:
#    path: /
#    defaults: { _controller: 'Hank\Controller\DefaultController::index' }

app_bank_homepage:
  path: /
  controller: Hank\UI\Symfony\Controller\BankHomePageController::index

app_bank_sign_in:
  path: /sign-in
  controller: Hank\UI\Symfony\Controller\SignInController::index

app_bank_sign_in_processing:
  path: /sign-in/processing
  controller: Hank\UI\Symfony\Controller\SignInController::signIn
  methods: [POST]

app_bank_sign_up:
  path: /sign-up
  controller: Hank\UI\Symfony\Controller\SignUpController::index

app_bank_sign_up_processing:
  path: /sign-up/processing
  controller: Hank\UI\Symfony\Controller\SignUpController::signUp
  methods: [POST]

app_bank_sign_out:
  path: /sign-out
  controller: Hank\UI\Symfony\Controller\SignOutController::index

app_bank_client_panel:
  path: /client-panel
  controller: Hank\UI\Symfony\Controller\ClientPanelController::index

app_bank_pay_in_client_panel:
  path: /client-panel/pay-in
  controller: Hank\UI\Symfony\Controller\PayInController::index

app_bank_pay_in_processing:
  path: /client-panel/pay-in-processing
  controller: Hank\UI\Symfony\Controller\PayInController::payIn
  methods: [POST]

app_bank_pay_out_client_panel:
  path: /client-panel/pay-out
  controller: Hank\UI\Symfony\Controller\PayOutController::index

app_bank_pay_out_processing:
  path: /client-panel/pay-out-processing
  controller: Hank\UI\Symfony\Controller\PayOutController::payOut
  methods: [POST]
