#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

app_bank_homepage:
  path: /
  controller: App\UI\Symfony\Controller\BankHomePage::index

app_bank_sign_in:
  path: /sign-in
  controller: App\UI\Symfony\Controller\SignIn::index

app_bank_sign_in_processing:
  path: /sign-in/processing
  controller: App\UI\Symfony\Controller\SignIn::signIn
  methods: [POST]

app_bank_sign_out:
  path: /sign-out
  controller: App\UI\Symfony\Controller\SignOut::index

app_bank_client_panel:
  path: /client-panel
  controller: App\UI\Symfony\Controller\ClientPanel::index

app_bank_pay_in_client_panel:
  path: /client-panel/pay-in
  controller: App\UI\Symfony\Controller\PayIn::index

app_bank_pay_in_processing:
  path: /client-panel/pay-in-processing
  controller: App\UI\Symfony\Controller\PayIn::payIn
  methods: [POST]
